spring.application.name=Order-Service


spring.datasource.url=jdbc:postgresql://localhost:5433/ecommerce
spring.datasource.username=${YOUR_USERNAME}
spring.datasource.password=${YOUR_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver


spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Must match the secret used by the User Service when signing tokens
jwt.secret=${JWT_SECRET:superSecretAccessKey2026!}

# Kafka Configuration
spring.kafka.bootstrap-servers=${KAFKA_URL:localhost:9092}
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.StringSerializer

# Payment Service Config
payment-service.url=${PAYMENT_SERVICE_URL:http://localhost:3002/api/payments}

# Resilience4j Circuit Breaker Config for Payment Service
resilience4j.circuitbreaker.instances.paymentService.registerHealthIndicator=true
resilience4j.circuitbreaker.instances.paymentService.slidingWindowSize=5
resilience4j.circuitbreaker.instances.paymentService.minimumNumberOfCalls=3
resilience4j.circuitbreaker.instances.paymentService.permittedNumberOfCallsInHalfOpenState=3
resilience4j.circuitbreaker.instances.paymentService.waitDurationInOpenState=10s
resilience4j.circuitbreaker.instances.paymentService.failureRateThreshold=50
resilience4j.circuitbreaker.instances.paymentService.recordExceptions=org.springframework.web.client.HttpServerErrorException,java.net.ConnectException,org.springframework.web.client.ResourceAccessException
