apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
  labels:
    app: user-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
        - name: user-service
          image: user-service:latest
          imagePullPolicy: Never
          env:
            - name: PORT
              value: "5000"
            - name: DB_USER
              value: "postgres"
            - name: DB_PASSWORD
              value: "password123"
            - name: DB_HOST
              value: "postgres"
            - name: DB_PORT
              value: "5432"
            - name: DB_NAME
              value: "khaana_khazana"
            - name: JWT_SECRET
              value: "superSecretAccessKey2026!"
          ports:
            - containerPort: 5000
              name: user-service
---
apiVersion: v1
kind: Service
metadata:
  name: user-service
spec:
  selector:
    app: user-service
  ports:
    - port: 5000
      targetPort: 5000
  type: ClusterIP
